#!/usr/bin/env bash

# This gets replaced by bin/compile for DRY purposes.
export LEIN_VERSION="##LEIN_VERSION##"

LEIN_JVM_OPTS="$LEIN_JVM_OPTS -Duser.home=$HOME -Dleiningen.original.pwd=$PWD"
LEIN_JAR=".lein/leiningen-$LEIN_VERSION-standalone.jar"

# Prefer JVM_OPTS, but fall back to JAVA_OPTS for compatibility
export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"

# apply context specific CLASSPATH entries
if [ -r .lein-classpath ]; then
    CLASSPATH="`cat .lein-classpath`:$CLASSPATH"
fi

CLASSPATH="$CLASSPATH:$LEIN_JAR"

TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"

java $LEIN_JVM_OPTS -cp "$CLASSPATH" \
    -client -XX:+TieredCompilation \
    -Dleiningen.trampoline-file=$TRAMPOLINE_FILE \
    clojure.main -m leiningen.core.main "$@"

EXIT_CODE=$?

if [ -r $TRAMPOLINE_FILE ]; then
    TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
    rm $TRAMPOLINE_FILE
    exec sh -c "exec $TRAMPOLINE"
else
    exit $EXIT_CODE
fi
